### ISSUE TITLE
Can't get it running on Linux Mint 19 Cinnamon

### ISSUE THREAD

**Issue by BillDietrich** [dlenski/python-vipaccess#16]
I'm a n00b; not sure if I'm doing something wrong, or what info you need.  I'm following instructions in https://chefkochblog.wordpress.com/2018/06/04/how-to-use-totp-with-your-paypal-account/ or in the README file.

Tried one way, got this:

    $ pip install .
    Processing /home/user1/python-vipaccess
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
        ImportError: No module named setuptools
        
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-5G6i_3-build/

Tried another way, was able to install docker.io package, but got this:

    $ docker run --rm kayvan/vipaccess provision -p -t VSST
   
    Command 'docker' not found, but can be installed with:

    sudo apt install docker.io

**Comment by dlenski** [comment]
> ```Huh, you managed to

**Comment by dlenski** [comment]
>```
>    ImportError: No module named setuptools
>```

This must be a completely new Linux system with nothing else installed on it, because it's hard to install Python these days *without* `setuptools`.

You need to `pip install setuptools`. 

Also, it's much preferred these days to use Python 3.x (which includes things like `setuptools` out-of-the-box) rather than Python 2.7, but that's a whole 'nother story.

**Comment by BillDietrich** [comment]
Okay, thanks, "pip install setuptools" got me past that point.

I installed Mint about a month ago.  Have installed a couple of dozen apps since then, most out of the Software Manager.

**Comment by BillDietrich** [comment]
Well, still stuck:

    user1@laptop1:~/python-vipaccess$ pip install .
    Processing /home/user1/python-vipaccess
    Collecting lxml (from python-vipaccess==0.3.0)
      Using cached https://files.pythonhosted.org/packages/e5/14            /f4343239f955442da9da1919a99f7311bc5627522741bada61b2349c8def/lxml-4.2.5-cp27-cp27mu-manylinux1_x86_64.whl
    Collecting oath (from python-vipaccess==0.3.0)
      Using cached https://files.pythonhosted.org/packages/64/19    /67fa93580c7fab35fca87dd51952d6255514a024b6add66e4c7769ed9d8c/oath-1.4.1.tar.gz
    Collecting pycryptodome (from python-vipaccess==0.3.0)
      Using cached https://files.pythonhosted.org/packages/40/26    /1546cda8b55c08001c9100c031bd1be4c93edb18bee788877f7e23fc1ecd/pycryptodome-3.6.6-cp27-    cp27mu-manylinux1_x86_64.whl
    Collecting requests (from python-vipaccess==0.3.0)
      Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
    Collecting idna<2.8,>=2.5 (from requests->python-vipaccess==0.3.0)
      Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
    Collecting certifi>=2017.4.17 (from requests->python-vipaccess==0.3.0)
      Using cached https://files.pythonhosted.org/packages/df/f7/04fee6ac349e915b82171f8e23cee63644d83663b34c539f7a09aed18f9e/certifi-2018.8.24-py2.py3-none-any.whl
    Collecting chardet<3.1.0,>=3.0.2 (from requests->python-vipaccess==0.3.0)
      Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
    Collecting urllib3<1.24,>=1.21.1 (from requests->python-vipaccess==0.3.0)
      Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
    Building wheels for collected packages: python-vipaccess, oath
      Running setup.py bdist_wheel for python-vipaccess ... error
      Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-90OsJV-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpslnSaSpip-wheel- --python-tag cp27:
      usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: -c --help [cmd1 cmd2 ...]
         or: -c --help-commands
         or: -c cmd --help
  
      error: invalid command 'bdist_wheel'
  
      ----------------------------------------
      Failed building wheel for python-vipaccess
      Running setup.py clean for python-vipaccess
      Running setup.py bdist_wheel for oath ... error
      Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-uCJ1fZ/oath/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpaq2hc7pip-wheel- --python-tag cp27:
      usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: -c --help [cmd1 cmd2 ...]
         or: -c --help-commands
         or: -c cmd --help
      
      error: invalid command 'bdist_wheel'
      
      ----------------------------------------
      Failed building wheel for oath
      Running setup.py clean for oath
    Failed to build python-vipaccess oath
    Installing collected packages: lxml, oath, pycryptodome, idna, certifi, chardet, urllib3, requests, python-vipaccess
      Running setup.py install for oath ... done
      Running setup.py install for python-vipaccess ... done
    Successfully installed certifi-2018.8.24 chardet-3.0.4 idna-2.7 lxml-4.2.5 oath-1.4.1     pycryptodome-3.6.6 python-vipaccess-0.3.0 requests-2.19.1 urllib3-1.23

**Comment by BillDietrich** [comment]
I'm using whatever came with Linux Mint 19 by default.

I got past this problem a while ago.  Someone else told me
what to install, I forget what it was.

Thanks,

Bill Dietrich   bill_dietrich@protonmail.com  https://www.billdietrich.me/
PGP public key available at https://api.protonmail.ch/pks/lookup?op=get&search=[bill_dietrich@protonmail.com](mailto:username@protonmail.com)

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
