### ISSUE TITLE
Something went wrong--the token is invalid

### ISSUE THREAD

**Issue by dwlocks** [dlenski/python-vipaccess#2]
I've used this lib/script in the past to configure a otp generator for VIP, and in the past it worked.  However when I attempt to provision new credentials, I get this error:
Something went wrong--the token is invalid.

This seems to mean that there's a problem with the guts of the credential provisioning process.  I put a few print statements  into the main script, and the returns from symantec are successful, but I don't know enough troubleshoot the content.

Does anyone else see this behavior?  Or perhaps symantec changed something about how their provisioning requests are structured?  I'm willing to spend some time troubleshooting, if I get some direction.

**Comment by dlenski** [comment]
I am thinking that @zecoj's commit 34b6ce6 will fix this. (It looks like the token-checking URL changed.)
