### ISSUE TITLE
test_url returning 404, all tokens report invalid

### ISSUE THREAD

**Issue by cheesy** [dlenski/python-vipaccess#23]
The test URL (https://idprotect.vip.symantec.com/testtoken.v) has been taken down. Every call now says the "token is invalid", though the tokens are fine if I comment out that code.

It looks like there's still a validator at https://idprotect.vip.symantec.com. Debugging with chrome shows a POST to https://idprotect.vip.symantec.com/otpCheck with fields cred: VSSTXXX and cr1 - cr6 for the 6 digits of the code.

**Comment by dlenski** [comment]
Thanks, that's good to know! Could you submit a PR to modify the token-check call appropriately?

**Comment by dlenski** [comment]
You must be running an anciiiiiiiiiient version of this repository.

The token-check URI was changed from the old one to a new, working one in 5d9eb5914526f3e6954d56414a42ae51b1fc6c58, back in 2017. :man_shrugging:

**Comment by cheesy** [comment]
*ugh* I accidentally installed the default version from pip, instead of the version I cloned from your repo. Sorry for the noise.
