### ISSUE TITLE
Feature/Improvement

### ISSUE THREAD

**Issue by JoelAzaria** [dlenski/python-vipaccess#26]
Hey now.  
Found your tool being hosted here: https://jakebarn.es/paypal
and was a great help.

One small point is that if you use a TOTP app that can't scan a QR code (e.g desktop app like Authy, or your camera is busted/disabled) you need the secret by itself to enter into the app.

I was able to extract it from the "Import URL" given but it might be helpful to some users to simply return this value on a line by itself.

Thanks and thank you for making this tool.  Helped me greatly.
J.

**Comment by dlenski** [comment]
> Found your tool being hosted here: https://jakebarn.es/paypal

Huh. I didn't create that site. ¯\\\_\(ツ\)\_/¯

I've _thought_ about putting something like this together, but never got around to it. Good idea by @DuBistKomisch :+1:

> I was able to extract it from the "Import URL" given but it might be helpful to some users to simply return this value on a line by itself.

Perhaps submit a PR on @DuBistKomisch's code?
https://github.com/DuBistKomisch/jakebarnes/blob/master/src/main.rs#L97-L115

**Comment by DuBistKomisch** [comment]
Thanks for the ping @dlenski!

Just quickly made this change since it's pretty simple, try it out @JoelAzaria

**Comment by dlenski** [comment]
While you're at it, @DuBistKomisch, you can make the output a little more user-friendly by making the URL look like `otpauth://email_address:token_serial_number`, which will cause most authenticator apps to show both the address and the serial number on separate lines. That way the user will have the bit of information needed to register the token without recording it separately…

For example, FreeOTP:

![FreeOTP](https://freeotp.github.io/img/android.png)

**Comment by DuBistKomisch** [comment]
Good point, I'll admit I was pretty confused by this page: https://github.com/google/google-authenticator/wiki/Key-Uri-Format

I changed it to `issuer:identity` so something like `PayPal:johnsmith@example.com`.

Is the serial number worth putting in somewhere?

**Comment by dlenski** [comment]
> Good point, I'll admit I was pretty confused by this page: https://github.com/google/google-authenticator/wiki/Key-Uri-Format

Me too. You're not the only one.

> Is the serial number worth putting in somewhere?

The user needs the serial number to register the VIPAccess token with Paypal (or whatever else they're using it with), which is why `vipaccess` itself includes it in the URL:

![screenshot from 2019-01-11 18-44-50](https://user-images.githubusercontent.com/128716/51068296-02c00e80-15d1-11e9-8e50-ab9aa957952c.png)

`vipaccess provision` already has a `-i ISSUER` option to modify that field in the output. It'd be trivial to modify it to be able to tweak any other field via command-line options, as well.

**Comment by DuBistKomisch** [comment]
I spit out the serial number on the website separately, so if it's only needed for the initial registration that should be enough.

Latest version of your fork isn't on pypi it seems, 0.3.0 doesn't have that flag.

**Comment by JoelAzaria** [comment]
> > Found your tool being hosted here: https://jakebarn.es/paypal
> 
> Huh. I didn't create that site. ¯\_(ツ)_/¯

I assume that a "Jake Barnes" created that site, I think using your tool/fork (since it's linked on his site)
> 
> I've _thought_ about putting something like this together, but never got around to it. Good idea by @DuBistKomisch 👍
> 
> > I was able to extract it from the "Import URL" given but it might be helpful to some users to simply return this value on a line by itself.
> 
> Perhaps submit a PR on @DuBistKomisch's code?
> https://github.com/DuBistKomisch/jakebarnes/blob/master/src/main.rs#L97-L115

Unfortunately actually *coding* is beyond my skillset.  I'm limited to reporting (and testing if it's layman/end-user level.)

**Comment by DuBistKomisch** [comment]
haha yeah it'd be nice if it showed name and username

no worries, you can probably close the issue now
