### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by Calorion** [dlenski/python-vipaccess#32]
Trying to install in macOS Mojave, I received `error: could not create '/Library/Python/2.7/site-packages/lxml': Permission denied` after executing 'pip3 install python-vipaccess'. Fine; instead I executed `pip3 install python-vipaccess —user` which fixed that. But then when I tried to run vipaccess with `vipaccess provision`, I get `vipaccess: command not found`. Shouldn't the installer have added a link to the executable to one of my $PATH directories?

**Comment by dlenski** [comment]
> Trying to install in macOS Mojave, I received `error: could not create '/Library/Python/2.7/site-packages/lxml': Permission denied` after executing 'pip3 install python-vipaccess'.

Something must be quite screwed up in your Python installation. `pip3` (that's the `pip` for Python **3.x**) should _not_ be touching a directory with `Python/2.7` in the path.

> Shouldn't the installer have added a link to the executable to one of my $PATH directories?

Yes.

**Comment by Calorion** [comment]
I don’t see what could have gone wrong with my installation. It’s a relatively fresh installation of Mojave; I haven’t messed with Python that I recall. 

But this doesn’t seem to be a problem with vipaccess, so…nevermind, I guess?

**Comment by dlenski** [comment]
I do not use macOS, and I know very little about how Python is packaged and distributed for it (beyond the fact that most users install it with [homebrew](https://brew.sh/)). :man_shrugging:

But it _definitely_ doesn't make any sense that the Python **3.x** `pip` is trying to install things in a directory for Python **2.7** libraries.

Perhaps you can post more details of how you installed Python3, and see if any other macOS users can shed any light?

**Comment by Calorion** [comment]
I didn't install Python3. That's probably the problem.
