### ISSUE TITLE
Getting different codes using the same dotfile

### ISSUE THREAD

**Issue by fjarenales** [dlenski/python-vipaccess#33]
Hi,

I installed python-vipaccess in two unix distributions: one Ubuntu, one Centos. Using the same dotfile, I'm getting different access codes. Do you know if this is because of libraries? I used pip3 and python 3.6.8 in both servers.

Any suggestion?

Thanks,

Javier

**Comment by dlenski** [comment]
No idea what could cause this, other than a large clock skew between the two systems.

If that's not it, try this patch:

```diff
diff --git a/vipaccess/cli.py b/vipaccess/cli.py
index 25b1229..d7cb7b9 100644
--- a/vipaccess/cli.py
+++ b/vipaccess/cli.py
@@ -122,10 +122,12 @@ def show(p, args):
             if 'expiry' in d: print('Token expiration: %s' % d['expiry'], file=sys.stderr)
             sys.stderr.write('\n')
 
+    print("*** encoded secret: %s ****" % secret)
     try:
         key = oath._utils.tohex( oath.google_authenticator.lenient_b32decode(secret) )
     except Exception as e:
         p.error('error interpreting secret as base32: %s' % e)
+    print("*** decoded key: %s ****" % key)
     print(oath.totp(key))
 
 def main():
```

With this patch, does it print identical values for both the encoded and decoded versions of the secret, on both systems?

**Comment by fjarenales** [comment]
Nevermind! My fault. There was a time gap between both servers.
