### ISSUE TITLE
How to add vipaccess to path?

### ISSUE THREAD

**Issue by lueenavarro** [dlenski/python-vipaccess#34]
i get vipaccess: command not found. How do I manually add it to the path? I'm using miniconda python3 and on ubuntu 18.04.2. I installed via "pip3 install python-vipaccess"

**Comment by dlenski** [comment]
Can you give more details on your environment?

With the standard Ubuntu 18.04 packages…

* `pip3 --user` will install CLI entry-point links in `~/.local/bin`
* The default `~/.profile` will include that directory in your path
* Most shells (including the default `bash`) will include `~/.profile` at startup

Does that match what you're seeing?

**Comment by lingxiangwu** [comment]
@lueenavarro  I guess what you need to do is:  `python3 -m vipaccess`

**Comment by romitathakur** [comment]
Hi when i am trying to do provision(vipaccess2 provision -t SYMC) its saying command not found for me on linux server. Can you tell me where i can execute this command ?

**Comment by dlenski** [comment]
> `vipaccess2 provision -t SYMC`

`vipaccess2`…?

**Comment by romitathakur** [comment]
> > `vipaccess2 provision -t SYMC`
> 
> `vipaccess2`…? Why "2"?
> 
> @romitathakur, you've [clearly done this successfully before](https://github.com/dlenski/python-vipaccess/issues/39#issuecomment-635109468).

@dlenski Hi, its done now may issue was with python installation directory.
Vipaccess2  was doing because was trying with vipaccess2 lib.
Also i have done it successfully in my local system was trying to do same on server.
