### ISSUE TITLE
Something went wrong--the token is invalid

### ISSUE THREAD

**Issue by MysteryDash** [dlenski/python-vipaccess#4]

**Comment by dlenski** [comment]
How are you invoking it, exactly? What version are you running exactly?

There was a patch for this issue about a month ago.

**Comment by MysteryDash** [comment]
Yes, but it looks like that issue is back.
I'm using the last version (I just cloned the repo) and I'm running it as
suggested : vipaccess provision (I also tried using the o and t parameters
in case these were necessary).

2017-04-23 19:25 GMT+02:00 Dan Lenski <notifications@github.com>:

**Comment by dlenski** [comment]
> Yes, but it looks like that issue is back.
> I'm using the last version (I just cloned the repo) and I'm running it as
suggested : vipaccess provision (I also tried using the o and t parameters
in case these were necessary).

I can't reproduce it. It's working fine for me.

Try adding a `print` statement to `check_token()` and see what the output looks like when you run `vipaccess provision`…?

```diff
diff --git a/vipaccess/provision.py b/vipaccess/provision.py
index 02fde28..67a1212 100644
--- a/vipaccess/provision.py
+++ b/vipaccess/provision.py
@@ -220,4 +220,5 @@ def check_token(token_id, secret):
     if "Your VIP Credential is working correctly" in token_check.text:
         return True
     else:
+        print(token_check.text)
         return False
```

**Comment by MysteryDash** [comment]
Instead of using print I used a file (it returns some html content, it looks like the homepage for vipacccess). The code I used is a basic open/write/close.
[file.txt](https://github.com/dlenski/python-vipaccess/files/950098/file.txt)

**Comment by dlenski** [comment]
Huh. Interesting, but I can't reproduce it so I have no idea what's wrong or how to fix it.

Perhaps you should try disabling the `check_token` procedure altogether…? Maybe the token works even if the Symantec checker _isn't_ working?

Or try to figure out if the `check_token` request is getting redirected?

**Comment by dlenski** [comment]
Also, the output you're seeing is not the homepage. And it contains the following contents:

```html
                        <span class="sixcode">Your VIP credential needs to be sync: VSST***</span>
```

Is it possible that your system clock is too far off, and that's why the token can't be checked?

**Comment by MysteryDash** [comment]
Yes, that's what happened (I don't know why the clock was 2 hours off but
adjusting it manually fixed that problem).
As a suggestion I could only say that it'd be great to use the time
provided by a reliable source instead of the user's clock, which as you can
see can't always be trusted.
Thanks.

Le 24 avr. 2017 02:07, "Dan Lenski" <notifications@github.com> a écrit :

Also, the output you're seeing is not the homepage. And it contains the
following contents:

                        <span class="sixcode">Your VIP credential
needs to be sync: VSST***</span>

Is it possible that your system clock is too far off, and that's why the
token can't be checked?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dlenski/python-vipaccess/issues/4#issuecomment-296498907>,
or mute the thread

**Comment by dlenski** [comment]
> As a suggestion I could only say that it'd be great to use the time
provided by a reliable source instead of the user's clock, which as you can
see can't always be trusted.

What other time source could be used for this?

**Comment by dlenski** [comment]
I modified the code to just warn, rather than fail, if the token can't be validated. I think that should be good enough for now.
