### ISSUE TITLE
Mention what the default TOKEN_MODEL is

### ISSUE THREAD

**Issue by jidanni** [dlenski/python-vipaccess#41]
README.md says
```
  -t TOKEN_MODEL, --token-model TOKEN_MODEL
                        VIP Access token model. Often VSST (desktop token,
                        default) or VSMT (mobile token) or SYMC. Some clients
                        only accept one or the other...
```
OK, but this does not say what will happen if we don't use this option. E.g., will we get SYMC?

Or perhaps the default is chosen by the company at runtime? I have no idea.

**Comment by dlenski** [comment]
The default value is _right there in the code_, and will be immediately obvious if you simply search for the string `--token-model` [in this repo](https://github.com/dlenski/python-vipaccess/search?q=--token-model&unscoped_q=--token-model).

You're opening a lot of issues that relate to possible improvements to the documentation.

Why not give me a PR that fixes them instead?

**Comment by jidanni** [comment]
I see. I was distracted by the "Often" so never though the word "default" was lurking with its parenthesis. Indeed it was right there in my bug report text above all the time.

> Why not give me a PR that fixes them instead?

(The sad truth is I am gambling that I will only need to use this program one time in my life and have already uninstalled it. Well at least that will guarantee I won't open any fresh issues.)
