### ISSUE TITLE
vipaccess uri could be cleaner, and then an xargs example could be added to README.md

### ISSUE THREAD

**Issue by jidanni** [dlenski/python-vipaccess#46]
On README.md
```
Once you generate a token with vipaccess provision, use vipaccess uri to show the otpauth:// URI and qrencode to display that URI as a QR code:

$ qrencode -t UTF8 'otpauth://totp/VIP%20Access:VSSTXXXX?secret=YYYY&issuer=Symantec&algorith...
```

Actually all this could be done in one step,
`vipaccess uri | xargs qrencode -t UTF8`
if this
```
$ vipaccess uri | perl -pwe 's/\n/\\n/g;' #(just showing the \n's with perl for this issue.)
Token URI:\n\n    otpauth:
^^^^^^^^^^^^^^^^^^Unneeded frontal matter
```
could be removed. (Else we need to do
`$ vipaccess uri | sed '$!d' |xargs qrencode -t UTF8`)

**Comment by dlenski** [comment]
I have seen absolutely no use case for automating this behavior. Unless someone actually needs to automate it (in which case they can use the library instead of the CLI), I see no reason to make this human-readable output harder to read.
