### ISSUE TITLE
Mention function of login.symantec.com

### ISSUE THREAD

**Issue by jidanni** [dlenski/python-vipaccess#47]
As we read in
https://knowledge.broadcom.com/external/article/176136/set-up-vip-access-on-a-new-phone-with-sa.html
this might be a way users can
1. sign up with this, entering the official app's credentials
2. then add the vipaccess generated credentials

then one need not use the official app anymore... but maybe it only works for Broadcomm (who owns Symantec.)

So I hope README.md would mention what login.symantec.com is all about, and if it can somehow allow users to not need to call each company they were formerly using the official app with, to register the vipaccess generated credentials.

**Comment by dlenski** [comment]
> then one need not use the official app anymore... but maybe it only works for Broadcomm (who owns Symantec.)

I'm not sure what you mean here.

The _whole point_ of `python-vipaccess` is to prevent you from needing to use the official app. What part of this unclear?

> So I hope README.md would mention what login.symantec.com is all about, and if it can somehow allow users to not need to call each company they were formerly using the official app with, to register the vipaccess generated credentials.

Are you suggesting that it should be possible to take an existing token that's registered in the official VIP Access apps, and connected to a specific login… and start using it in `python-vipaccess` instead, without creating and registering new tokens?

I don't believe this is possible, and not sure if that's what the page you mention is actually claiming. Even if it is possible, it's likely that a whole 'nother chunk of the official apps' code would have to be reverse-engineered to do it. Contributions welcome.

**Comment by jidanni** [comment]
I am saying that most people:
1. Use the official app
1. Slowly realize that there must be a better way
1. Discover https://github.com/dlenski/python-vipaccess, and install it and get everything they need....
1. ... except they still need to make a call to their bank, etc. saying "Hi, I reinstalled all the apps (excreta excuse) so here is the new SYMCxxxxxxxx code..."

**Comment by dlenski** [comment]
I don't think there is a way around (4).

> It somewhat seems like: I just make and then verify an account on login.symantec.com with my old app (their official one, that I had installed before I discovered python-vipaccess), add a second verification with my new app (i.e., python-vipaccess), and then the two are seen as equivalent, so I don't need to contact my bank, insurance co., etc. Killed two birds with one stone.

Does this actually work?

**Comment by jidanni** [comment]
Well, no. I still had to call my bank. Okay I guess it's not really your responsibility to explain all the weird things that that company Symantec is doing. So I'll close this bug.
