### ISSUE TITLE
Online (web) generator for VIP QR codes

### ISSUE THREAD

**Issue by ttodua** [dlenski/python-vipaccess#49]
Just for case, to facilitate things, here is a link of web-based generator , based on this project 👍 

https://puvox.software/tools/symantec-vip-qr-code

**Comment by dlenski** [comment]
Would be nice if it had an option to vary the token type (e.g. `SYMC` vs. `VSMT`, etc.)

**Comment by ttodua** [comment]
hi dlenski,
 I will try to make the update , thanks.

**Comment by dlenski** [comment]
Appears that this site no longer works.

**Comment by ttodua** [comment]
Ah, sorry for being late. The ubuntu package update broke the tool and it was then fixed and works. 
Also, about your above comment :
`Would be nice if it had an option to vary the token type (e.g. SYMC vs. VSMT, etc.) `
Can you direct me what arguments does `--token-model` parameter accept, so i will add dropdown there too, to choose one of them

**Comment by dlenski** [comment]
> The ubuntu package update broke the tool and it was then fixed and works. (the subdomain was removed from link, so it is at the link given in first post )

Huh… which update broke it?

> I've added those features on the tool too, let me know your thoughts.

It looks good to me.
