### ISSUE TITLE
Make SYMC the default token model

### ISSUE THREAD

**Issue by jnahmias** [dlenski/python-vipaccess#51]
Hello,
Per the article at https://knowledge.broadcom.com/external/article?legacyId=TECH239895

> The VIP Access Toolbar token (VSST) is no longer available or supported.

I think it would be good to change the default to SYMC.

**Comment by dlenski** [comment]
> I think it would be good to change the default to SYMC.

Seems like a good idea indeed. Should be easy to create a PR for it (please remember to update the docs and tests in addition to the default for the CLI).
