### ISSUE TITLE
Decode existing Windows token?

### ISSUE THREAD

**Issue by hmlendea** [dlenski/python-vipaccess#54]
Hello,

Might be a bit off topic, but there we go...

Is there a way to decode the existing token from the Windows app, instead of generating a new one?
I'm guessing it is in `HKEY_CURRENT_USER\Software\Symantec\VIP Access Client\PrivateData`

**Comment by dlenski** [comment]
> Is there a way to decode the existing token from the Windows app, instead of generating a new one?
> I'm guessing it is in `HKEY_CURRENT_USER\Software\Symantec\VIP Access Client\PrivateData`

Possibly :man_shrugging: … but that's outside the scope of this project, which focuses on capturing the token secrets _at the time of token provisioning_.

My educated guess is that the on-disk token storage has multiple layers of platform- and version-specific obfuscation.

Is there any reason you can't just generate a new token? I've never seen a service using VIP Access for 2FA that _didn't_ make this relatively easy to do.

**Comment by hmlendea** [comment]
I was just trying to save the trouble of calling the dreaded support and wasting half a day to get it done :D I was hoping someone already "cracked" it.

Well, I'll just go through provisioning then using the method in the readme. Running the script went perfectly the first try, so all that's left is for them to register the token.

**Comment by dlenski** [comment]
> I was just trying to save the trouble of calling the dreaded support and wasting half a day to get it done :D I was hoping someone already "cracked" it.

Yep, quite understandable… I had to submit a manual request at a previous job once. The harder part was convincing a bunch of my _coworkers_ to do the same. :disappointed:

**Comment by hmlendea** [comment]
Got it working today. Got lucky and it didn't take all that long. I've generated the code with the Microsoft Authenticator and the [Authenticator extension for FireFox](https://github.com/Authenticator-Extension/Authenticator) just fine!
