### ISSUE TITLE
Security code?

### ISSUE THREAD

**Issue by attah** [dlenski/python-vipaccess#60]
The Symantec portal now seems to want a Credential ID *and* a security code (from the app).
Have you seen this before? Any idea what that might be?

**Comment by dlenski** [comment]
I'm not sure what you mean. `vipaccess provision` is still working fine, for me.

> The Symantec portal now seems to want a Credential ID and a security code (from the app).

What is "the Symantec portal" and how is it involved here?

**Comment by attah** [comment]
Oh, i'm stupid!
After googling an example i found a guide explaining it - they want the TOTP code already at registration.
I had no recollection of this.
And the images they use to show it just look nothing like the app anymore, so i thought it was something else that the app would produce along with the Credential ID.
(For reference, last image on the right: https://itsecurity.mssm.edu/vip-two-factor-setup/)
Sorry for the noise!
