### ISSUE TITLE
no issuer and added image

### ISSUE THREAD

**Issue by cthulhubuddha** [dlenski/python-vipaccess#62]
I generated a new VIP credential today and noticed there is a big difference between it and one i generated last year - 

Old:
otpauth://totp/VIP%20Access:SYMCYYYYYY?secret=<blah>&digits=6&algorithm=SHA1&issuer=Symantec&period=30

New:
otpauth://totp/VIP%20Access:SYMCXXXXXX?secret=<blah2>&digits=6&algorithm=SHA1&image=https%3A%2F%2Fraw.githubusercontent.com%2Fdlenski%2Fpython-vipaccess%2Fmaster%2Fvipaccess.png&period=30

Instead of 
&issuer=Symantec 

that has been replaced with 
&image=https%3A%2F%2Fraw.githubusercontent.com%2Fdlenski%2Fpython-vipaccess%2Fmaster%2Fvipaccess.png

I didn't find any open or closed issue here for this. I followed the exact same steps (vipaccess provision -p -t SYMC), why are the credentials different (besides the obvious SYMC code and secret keys)?

**Comment by dlenski** [comment]
> I didn't find any open or closed issue here for this. 

Seems like you didn't try very hard, since the relevant changes to the code are both in the _last 11_ commits:

- acf264e20d90b73bd9b3bec330ccbbc958dc4420 (fixes #53)
- 318cb7185ad5acde975aec3fa814c459002b9fb9.
