### ISSUE TITLE
What happens after expiration date?

### ISSUE THREAD

**Issue by smoochy** [dlenski/python-vipaccess#64]
Hey Dan,

first thanks for creating this wonderful tool!

I noticed this, after creating a credential:

`This credential expires on this date: 2026-02-25T09:03:40.151Z`

Added it to my 1password account to conviently access the service I am using it for.

So what does happen after that expiration date? Do I have to remember to renew it before it expires? Will the tokens being generated be invalid after that time?

Thanks for clarifying.

Kind Regards

**Comment by dlenski** [comment]
https://github.com/dlenski/python-vipaccess/issues/11#issuecomment-372829370

**Comment by smoochy** [comment]
Thank you for the reply and sorry for having asked the question which was already answered. I looked for "expiration", but probably didn't filter correctly, as no result was coming up. Must have set it to look only in open issues.
