### ISSUE TITLE
Question:  What happens at credential expiration date?

### ISSUE THREAD

**Issue by Amoeba00** [dlenski/python-vipaccess#66]
1 - Just found this via a [reddit post on USAA](https://www.reddit.com/r/USAA/comments/11ytn0c/protip_usaa_2fa_cybercode_sucks_heres_a/) - followed the steps and got it working with no issues.  Thanks to all your efforts for making this!

2 - When I generated the credential I noticed this in the output:  "This credential expires on this date:" with today's datetimestamp plus 3 years.  

So what happens in 3 years?  Will I need to generate a new credential from scratch or is this like a cert renewal process and I will need to generate a new TOTP code?

Thanks!

**Comment by dlenski** [comment]
> So what happens in 3 years? Will I need to generate a new credential from scratch or is this like a cert renewal process and I will need to generate a new TOTP code?

See #11, which I've now pinned, in particular https://github.com/dlenski/python-vipaccess/issues/11#issuecomment-372829370 and https://github.com/dlenski/python-vipaccess/issues/11#issuecomment-411638411
