### ISSUE TITLE
Retrieve secret key from mobile app

### ISSUE THREAD

**Issue by meehatpa** [dlenski/python-vipaccess#69]
First of all, thank you kind stranger for this wonderful app.

I would like to know how can I retrieve the secret key from my mobile app. I am trying to go down this path because Etrade customer service is non existent and I cannot add new codes in Etrade.

**Comment by dlenski** [comment]
> I would like to know how can I retrieve the secret key from my mobile app.

I don't know, and it's basically out of the scope of this project. See https://github.com/dlenski/python-vipaccess/issues/54#issuecomment-795888622 for more thoughts.

**Comment by meehatpa** [comment]
Thanks for the link.
