### ISSUE TITLE
PyCrypto dependency fails on Win10 Python 3.6

### ISSUE THREAD

**Issue by shadow651** [dlenski/python-vipaccess#9]
Small issue when using this on win10 with python (had to run a Ubuntu VM where it still works fine) it fails on the bdist_wheel creation.
**PyCrypto** is 'dead' according to this thread that has the same issue, should change dependency to **pycryptodome** if possible
https://github.com/dlitz/pycrypto/issues/218

I can confirm that pycryptodome installs fine on my win10.

**Comment by dlenski** [comment]
Thanks a lot!

**Comment by shadow651** [comment]
Thanks for the fix, you forgot to update the readme instructions for the dependencies though.

**Comment by avrajsri** [comment]
pip uninstall crypto
Delete "crypto" Folder [C:\Users\AppData\Local\Programs\Python\Python37\Lib\site-packages]
pip install crypto
pip uninstall pycryptodome
pip install pycryptodome

pip uninstall pycryptodomex
pip install pycryptodomex
pip uninstall cryptography
pip install cryptography

Rename Folder "crypto" to "Crypto" [C:\Users\AppData\Local\Programs\Python\Python37\Lib\site-packages]

Then Use "from Crypto.Cipher import AES"

**Comment by dlenski** [comment]
@avrajsri, what's this supposed to mean? What problem does it solve?
